# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SideDish' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SideDish
pod 'Toaster', :git => 'https://github.com/devxoul/Toaster.git', :branch => 'master'
end
